version: "3.9"

services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=dlcs
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=compositedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
