# Generated by Django 4.2.14 on 2026-07-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20220113_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
