name: DLCS Build, Test & Publish

on:
  push:
    branches: [ "main", "develop" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test-compositehandler:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - id: pre-commit
        uses: pre-commit/action@v3.0.1

      - id: docker-setup-buildx
        uses: docker/setup-buildx-action@v3

      - id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dlcs/compositehandler
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,enable=true,prefix=,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - id: docker-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker-build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          builder: ${{ steps.docker-setup-buildx.outputs.name }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          push: ${{ github.actor != 'dependabot[bot]' }}
